


export const OBTENER_TAREAS         = 'OBTENER_TAREAS';
export const FILTRO_TAREAS          = 'FILTRO_TAREAS';
export const TEXTO_NUEVA_TAREA      = 'TEXTO_NUEVA_TAREA';
export const EDITAR_TAREA           = 'EDITAR_TAREA';
export const VACIAR_EDITAR_TAREA    = 'VACIAR_EDITAR_TAREA';
export const TEXTO_EDITAR_TAREA     = 'TEXTO_EDITAR_TAREA';
export const STATUS_EDITAR_TAREA    = 'STATUS_EDITAR_TAREA';
export const ELIMINAR_TAREA         = 'ELIMINAR_TAREA';
export const CANCELAR_ELIMINAR_TAREA= 'CANCELAR_ELIMINAR_TAREA';